language: bash
sudo: required
dist: trusty
before_install:
  - sudo make dependencies
install:
  - make local-lib
script:
  - export PACKAGE=`perl -ne 'print $1 if /^Package:\s+(.+)/;' < debian/control`
  - export TEST_URL=app.psgi
  - prove -l -Ilocal/lib/perl5 -v
  - make release-file
  - sudo dpkg -i ${PACKAGE}_*.deb
  - sudo service ${PACKAGE} status
  - sudo service ${PACKAGE} restart
  - export TEST_URL=http://localhost:6027/
  - prove -Ilocal/lib/perl5 -l -v
cache: apt
after_failure:
  - tail -200 /var/log/${PACKAGE}/error.log
  - tail -200 /var/log/${PACKAGE}/access.log
  - curl -i http://localhost:6027/ 
before_deploy:
  - export RELEASE_PKG_FILE=$(ls *.deb)
  - echo "deploying $RELEASE_PKG_FILE"
deploy:
  provider: releases
  api_key:
    secure: SyeWdiJJ6+9X+KypNSe18mPDFslzXJQkA+Ihx3fagZqRxhX5XC8OcjjAjxEjiBc1bMH4zJCcX+k1ZoqRPq4M/stuNjjfav0eraGGeTVE9VSlPTprN08tj+HnLhbiZ5ymAH4yi8l63J52pU1vV63V8k7F9S9FTF1tC5oFV4aMbQo=
  file_glob: true
  skip_cleanup: true
  file: "${RELEASE_PKG_FILE}"
  on:
    tags: true
