language: perl
perl:
    - 5.14
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install fakeroot dpkg-dev
    - sudo apt-get install `perl -nE 'next unless $_ =~ s/^Depends:\s+//; $_ =~ s/[, ]+|\([^)]+\)/ /g; say' < debian/control`
install:
    - sudo apt-get install cpanminus
    - sudo cpanm Carton
    - carton install --deployment
script:
    - make debian-package
    - sudo dpkg -i coverdienst_*.deb
    - sudo service coverdienst status
    - carton exec prove -Ilib --verbose 
cache: apt
